name: continuous-integration-workflow
on: [push]

jobs:
    build-server:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - name: set up JDK 1.8
              uses: actions/setup-java@v1
              with:
                java-version: 1.8
            - name: Build with Gradle
              run: ./gradlew server:build

    build-android:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - name: set up JDK 1.8
              uses: actions/setup-java@v1
              with:
                java-version: 1.8
            - name: Build with Gradle
              run: ./gradlew assembleDebug

    build-ios:
        runs-on: macos-latest
        steps:
            - uses: actions/checkout@v1
            - name: Select Xcode version
              run: sudo xcode-select -s '/Applications/Xcode_11.2.1.app/Contents/Developer'
            - name: Show Xcode version
              run: xcodebuild -version
            - name: Build
              working-directory: ./iosApp
              run: xcodebuild -scheme iosApp -sdk iphonesimulator -configuration Debug build
              env:
                  GRADLE_OPTS: '-Dorg.gradle.jvmargs="-Xmx2048m"'
